/* automatically generated by rust-bindgen */
// Linking happens at build.rs file

extern "C" {
    pub fn binomial_coef(n: f64, k: f64) -> f64;
}
extern "C" {
    pub fn log_binomial_coef(n: f64, k: f64) -> f64;
}
extern "C" {
    pub fn beta(a: f64, b: f64) -> f64;
}
extern "C" {
    pub fn lbeta(a: f64, b: f64) -> f64;
}
extern "C" {
    pub fn tgamma(x: f64) -> f64;
}
extern "C" {
    pub fn lgamma(x: f64) -> f64;
}
extern "C" {
    pub fn lmgamma(a: f64, p: f64) -> f64;
}
extern "C" {
    pub fn erf(x: f64) -> f64;
}
extern "C" {
    pub fn incomplete_beta(a: f64, b: f64, z: f64) -> f64;
}
extern "C" {
    pub fn incomplete_gamma(a: f64, x: f64) -> f64;
}
extern "C" {
    pub fn erf_inv(p: f64) -> f64;
}
extern "C" {
    pub fn incomplete_beta_inv(a: f64, b: f64, p: f64) -> f64;
}
extern "C" {
    pub fn incomplete_gamma_inv(a: f64, p: f64) -> f64;
}
