[package]
name = "statslib"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.31.0", features = ["serde-serialize", "sparse"] }
simba="0.7.1"
special = "0.8.1"
rand = "0.8.5"
rand_distr = "0.4.3"
