/* automatically generated by rust-bindgen */

pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _flags2: ::std::os::raw::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub __pad5: usize,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
extern "C" {
    pub fn gsl_error(
        reason: *const ::std::os::raw::c_char,
        file: *const ::std::os::raw::c_char,
        line: ::std::os::raw::c_int,
        gsl_errno: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn gsl_stream_printf(
        label: *const ::std::os::raw::c_char,
        file: *const ::std::os::raw::c_char,
        line: ::std::os::raw::c_int,
        reason: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn gsl_strerror(gsl_errno: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
pub type gsl_error_handler_t =
    ::std::option::Option<
        unsafe extern "C" fn(reason: *const ::std::os::raw::c_char,
                             file: *const ::std::os::raw::c_char,
                             line: ::std::os::raw::c_int,
                             gsl_errno: ::std::os::raw::c_int),
    >;
pub type gsl_stream_handler_t =
    ::std::option::Option<
        unsafe extern "C" fn(label: *const ::std::os::raw::c_char,
                             file: *const ::std::os::raw::c_char,
                             line: ::std::os::raw::c_int,
                             reason: *const ::std::os::raw::c_char),
    >;
extern "C" {
    pub fn gsl_set_error_handler(new_handler: gsl_error_handler_t) -> gsl_error_handler_t;
}
extern "C" {
    pub fn gsl_set_error_handler_off() -> gsl_error_handler_t;
}
extern "C" {
    pub fn gsl_set_stream_handler(new_handler: gsl_stream_handler_t) -> gsl_stream_handler_t;
}
extern "C" {
    pub fn gsl_set_stream(new_stream: *mut FILE) -> *mut FILE;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gsl_block_struct {
    pub size: usize,
    pub data: *mut f64,
}
pub type gsl_block = gsl_block_struct;
extern "C" {
    pub fn gsl_block_alloc(n: usize) -> *mut gsl_block;
}
extern "C" {
    pub fn gsl_block_calloc(n: usize) -> *mut gsl_block;
}
extern "C" {
    pub fn gsl_block_free(b: *mut gsl_block);
}
extern "C" {
    pub fn gsl_block_fread(stream: *mut FILE, b: *mut gsl_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_fwrite(stream: *mut FILE, b: *const gsl_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_fscanf(stream: *mut FILE, b: *mut gsl_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_fprintf(
        stream: *mut FILE,
        b: *const gsl_block,
        format: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fread(
        stream: *mut FILE,
        b: *mut f64,
        n: usize,
        stride: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fwrite(
        stream: *mut FILE,
        b: *const f64,
        n: usize,
        stride: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fscanf(
        stream: *mut FILE,
        b: *mut f64,
        n: usize,
        stride: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fprintf(
        stream: *mut FILE,
        b: *const f64,
        n: usize,
        stride: usize,
        format: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_size(b: *const gsl_block) -> usize;
}
extern "C" {
    pub fn gsl_block_data(b: *const gsl_block) -> *mut f64;
}
