[package]
name = "mcmclib"
version = "0.0.1"
authors = ["Diego Lima <lima.ds@outlook.com>"]
edition = "2018"
license = "LGPL-3.0"
keywords = ["statistics", "probability", "inference"]
categories = ["science"]
# build = "build.rs"
# links = "gsl"
publish = ["crates-io"]
readme = "README.md"
description = "Composable abstractions to build probabilistic models and inference algorithms"

[dependencies]
nalgebra = { version = "0.31.0", features = ["rand"] }
simba="0.7.1"
# special = "0.8.1"
# itertools = "0.10.1"
# petgraph = "0.6.0"
# serde = { version = "1.0.111", features=["derive"] }
# serde_json = "1.0.55"
rand = "0.8.5"
rand_distr = "0.4.3"
# smallvec="1.9.0"
# csv = "1.1.3"
# postgres = "0.19.0"
# sqlparser = "0.5.1"
# rusqlite = "0.24.2"
# structopt = "0.3.19"
# anyhow = "1.0.32"
# thiserror = "1.0.20"
# argmin = { git="https://github.com/argmin-rs/argmin", features = ["nalgebral"] }
# argmin = "0.5.0"
num-traits = "0.2.14"
approx="0.5.1"
# abiparse = { path = "/home/diego/Downloads/abiparse" }
# either = "1.6.1"
# TODO replace by special
# mathru = "0.8.4"

# spade = "1.8.2"
# indicatif = "0.16.0"
# finitediff = "0.1.3"
# arraymap = "0.1.1"
# polars = "0.14.8"

# [build-dependencies]
# cc = "1.0.66"

# pg-extend = { version = "0.2.1", optional=true }
# levenberg-marquardt = "0.6.0"
# r_mathlib = "0.1.0"
# fann = "0.1.7"
# rust_decimal = { version = "1.3.0", features = ["postgres"] }

# To build with pgext, use
# RUSTFLAGS="-C link-arg=-undefineddynamic_lookup" PG_INCLUDE_PATH=/usr/include/postgresql/11/server cargo build --features pgext
# [features]
# gsl=[]
# pgext=[]
# api=[]
# sql=[]

# [[example]]
# name = "composition"
# path = "examples/composition.rs"

# [[example]]
# name = "sample"
# path = "examples/sample.rs"

# [[example]]
# name="approx"
# path = "examples/approx.rs"

# [[example]]
# name="logistic"
# path = "examples/logistic.rs"

# [[example]]
# name="multinormal"
# path = "examples/multinormal.rs"

# [[example]]
# name="mixture"
# path="examples/mixture.rs"
