use crate::foreign::gsl::block_double::*;
use crate::foreign::gsl::vector_double::*;

/* automatically generated by rust-bindgen */

extern "C" {
    pub fn gsl_error(
        reason: *const ::std::os::raw::c_char,
        file: *const ::std::os::raw::c_char,
        line: ::std::os::raw::c_int,
        gsl_errno: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn gsl_stream_printf(
        label: *const ::std::os::raw::c_char,
        file: *const ::std::os::raw::c_char,
        line: ::std::os::raw::c_int,
        reason: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn gsl_strerror(gsl_errno: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn gsl_set_error_handler(new_handler: gsl_error_handler_t) -> gsl_error_handler_t;
}
extern "C" {
    pub fn gsl_set_error_handler_off() -> gsl_error_handler_t;
}
extern "C" {
    pub fn gsl_set_stream_handler(new_handler: gsl_stream_handler_t) -> gsl_stream_handler_t;
}
extern "C" {
    pub fn gsl_set_stream(new_stream: *mut FILE) -> *mut FILE;
}
extern "C" {
    pub fn gsl_block_alloc(n: usize) -> *mut gsl_block;
}
extern "C" {
    pub fn gsl_block_calloc(n: usize) -> *mut gsl_block;
}
extern "C" {
    pub fn gsl_block_free(b: *mut gsl_block);
}
extern "C" {
    pub fn gsl_block_fread(stream: *mut FILE, b: *mut gsl_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_fwrite(stream: *mut FILE, b: *const gsl_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_fscanf(stream: *mut FILE, b: *mut gsl_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_fprintf(
        stream: *mut FILE,
        b: *const gsl_block,
        format: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fread(
        stream: *mut FILE,
        b: *mut f64,
        n: usize,
        stride: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fwrite(
        stream: *mut FILE,
        b: *const f64,
        n: usize,
        stride: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fscanf(
        stream: *mut FILE,
        b: *mut f64,
        n: usize,
        stride: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_raw_fprintf(
        stream: *mut FILE,
        b: *const f64,
        n: usize,
        stride: usize,
        format: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_block_size(b: *const gsl_block) -> usize;
}
extern "C" {
    pub fn gsl_block_data(b: *const gsl_block) -> *mut f64;
}
#[repr(C)]
pub struct _gsl_vector_view {
    pub vector: gsl_vector,
}
#[repr(C)]
pub struct _gsl_vector_const_view {
    pub vector: gsl_vector,
}
extern "C" {
    pub fn gsl_vector_alloc(n: usize) -> *mut gsl_vector;
}
extern "C" {
    pub fn gsl_vector_calloc(n: usize) -> *mut gsl_vector;
}
extern "C" {
    pub fn gsl_vector_alloc_from_block(
        b: *mut gsl_block,
        offset: usize,
        n: usize,
        stride: usize,
    ) -> *mut gsl_vector;
}
extern "C" {
    pub fn gsl_vector_alloc_from_vector(
        v: *mut gsl_vector,
        offset: usize,
        n: usize,
        stride: usize,
    ) -> *mut gsl_vector;
}
extern "C" {
    pub fn gsl_vector_free(v: *mut gsl_vector);
}
extern "C" {
    pub fn gsl_vector_view_array(v: *mut f64, n: usize) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_vector_view_array_with_stride(
        base: *mut f64,
        stride: usize,
        n: usize,
    ) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_vector_const_view_array(v: *const f64, n: usize) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_vector_const_view_array_with_stride(
        base: *const f64,
        stride: usize,
        n: usize,
    ) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_vector_subvector(v: *mut gsl_vector, i: usize, n: usize) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_vector_subvector_with_stride(
        v: *mut gsl_vector,
        i: usize,
        stride: usize,
        n: usize,
    ) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_vector_const_subvector(
        v: *const gsl_vector,
        i: usize,
        n: usize,
    ) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_vector_const_subvector_with_stride(
        v: *const gsl_vector,
        i: usize,
        stride: usize,
        n: usize,
    ) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_vector_set_zero(v: *mut gsl_vector);
}
extern "C" {
    pub fn gsl_vector_set_all(v: *mut gsl_vector, x: f64);
}
extern "C" {
    pub fn gsl_vector_set_basis(v: *mut gsl_vector, i: usize) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_fread(stream: *mut FILE, v: *mut gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_fwrite(stream: *mut FILE, v: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_fscanf(stream: *mut FILE, v: *mut gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_fprintf(
        stream: *mut FILE,
        v: *const gsl_vector,
        format: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_memcpy(
        dest: *mut gsl_vector,
        src: *const gsl_vector,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_reverse(v: *mut gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_swap(v: *mut gsl_vector, w: *mut gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_swap_elements(
        v: *mut gsl_vector,
        i: usize,
        j: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_max(v: *const gsl_vector) -> f64;
}
extern "C" {
    pub fn gsl_vector_min(v: *const gsl_vector) -> f64;
}
extern "C" {
    pub fn gsl_vector_minmax(v: *const gsl_vector, min_out: *mut f64, max_out: *mut f64);
}
extern "C" {
    pub fn gsl_vector_max_index(v: *const gsl_vector) -> usize;
}
extern "C" {
    pub fn gsl_vector_min_index(v: *const gsl_vector) -> usize;
}
extern "C" {
    pub fn gsl_vector_minmax_index(v: *const gsl_vector, imin: *mut usize, imax: *mut usize);
}
extern "C" {
    pub fn gsl_vector_add(a: *mut gsl_vector, b: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_sub(a: *mut gsl_vector, b: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_mul(a: *mut gsl_vector, b: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_div(a: *mut gsl_vector, b: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_scale(a: *mut gsl_vector, x: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_add_constant(a: *mut gsl_vector, x: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_equal(u: *const gsl_vector, v: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_isnull(v: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_ispos(v: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_isneg(v: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_isnonneg(v: *const gsl_vector) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_vector_get(v: *const gsl_vector, i: usize) -> f64;
}
extern "C" {
    pub fn gsl_vector_set(v: *mut gsl_vector, i: usize, x: f64);
}
extern "C" {
    pub fn gsl_vector_ptr(v: *mut gsl_vector, i: usize) -> *mut f64;
}
extern "C" {
    pub fn gsl_vector_const_ptr(v: *const gsl_vector, i: usize) -> *const f64;
}
#[repr(C)]
#[derive(Clone)]
pub struct gsl_matrix {
    pub size1: usize,
    pub size2: usize,
    pub tda: usize,
    pub data: *mut f64,
    pub block: *mut gsl_block,
    pub owner: ::std::os::raw::c_int,
}
#[repr(C)]
pub struct _gsl_matrix_view {
    pub matrix: gsl_matrix,
}
pub type gsl_matrix_view = _gsl_matrix_view;
#[repr(C)]
pub struct _gsl_matrix_const_view {
    pub matrix: gsl_matrix,
}
pub type gsl_matrix_const_view = _gsl_matrix_const_view;
extern "C" {
    pub fn gsl_matrix_alloc(n1: usize, n2: usize) -> *mut gsl_matrix;
}
extern "C" {
    pub fn gsl_matrix_calloc(n1: usize, n2: usize) -> *mut gsl_matrix;
}
extern "C" {
    pub fn gsl_matrix_alloc_from_block(
        b: *mut gsl_block,
        offset: usize,
        n1: usize,
        n2: usize,
        d2: usize,
    ) -> *mut gsl_matrix;
}
extern "C" {
    pub fn gsl_matrix_alloc_from_matrix(
        m: *mut gsl_matrix,
        k1: usize,
        k2: usize,
        n1: usize,
        n2: usize,
    ) -> *mut gsl_matrix;
}
extern "C" {
    pub fn gsl_vector_alloc_row_from_matrix(m: *mut gsl_matrix, i: usize) -> *mut gsl_vector;
}
extern "C" {
    pub fn gsl_vector_alloc_col_from_matrix(m: *mut gsl_matrix, j: usize) -> *mut gsl_vector;
}
extern "C" {
    pub fn gsl_matrix_free(m: *mut gsl_matrix);
}
extern "C" {
    pub fn gsl_matrix_submatrix(
        m: *mut gsl_matrix,
        i: usize,
        j: usize,
        n1: usize,
        n2: usize,
    ) -> _gsl_matrix_view;
}
extern "C" {
    pub fn gsl_matrix_row(m: *mut gsl_matrix, i: usize) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_matrix_column(m: *mut gsl_matrix, j: usize) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_matrix_diagonal(m: *mut gsl_matrix) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_matrix_subdiagonal(m: *mut gsl_matrix, k: usize) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_matrix_superdiagonal(m: *mut gsl_matrix, k: usize) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_matrix_subrow(
        m: *mut gsl_matrix,
        i: usize,
        offset: usize,
        n: usize,
    ) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_matrix_subcolumn(
        m: *mut gsl_matrix,
        j: usize,
        offset: usize,
        n: usize,
    ) -> _gsl_vector_view;
}
extern "C" {
    pub fn gsl_matrix_view_array(base: *mut f64, n1: usize, n2: usize) -> _gsl_matrix_view;
}
extern "C" {
    pub fn gsl_matrix_view_array_with_tda(
        base: *mut f64,
        n1: usize,
        n2: usize,
        tda: usize,
    ) -> _gsl_matrix_view;
}
extern "C" {
    pub fn gsl_matrix_view_vector(v: *mut gsl_vector, n1: usize, n2: usize) -> _gsl_matrix_view;
}
extern "C" {
    pub fn gsl_matrix_view_vector_with_tda(
        v: *mut gsl_vector,
        n1: usize,
        n2: usize,
        tda: usize,
    ) -> _gsl_matrix_view;
}
extern "C" {
    pub fn gsl_matrix_const_submatrix(
        m: *const gsl_matrix,
        i: usize,
        j: usize,
        n1: usize,
        n2: usize,
    ) -> _gsl_matrix_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_row(m: *const gsl_matrix, i: usize) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_column(m: *const gsl_matrix, j: usize) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_diagonal(m: *const gsl_matrix) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_subdiagonal(m: *const gsl_matrix, k: usize) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_superdiagonal(m: *const gsl_matrix, k: usize)
        -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_subrow(
        m: *const gsl_matrix,
        i: usize,
        offset: usize,
        n: usize,
    ) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_subcolumn(
        m: *const gsl_matrix,
        j: usize,
        offset: usize,
        n: usize,
    ) -> _gsl_vector_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_view_array(
        base: *const f64,
        n1: usize,
        n2: usize,
    ) -> _gsl_matrix_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_view_array_with_tda(
        base: *const f64,
        n1: usize,
        n2: usize,
        tda: usize,
    ) -> _gsl_matrix_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_view_vector(
        v: *const gsl_vector,
        n1: usize,
        n2: usize,
    ) -> _gsl_matrix_const_view;
}
extern "C" {
    pub fn gsl_matrix_const_view_vector_with_tda(
        v: *const gsl_vector,
        n1: usize,
        n2: usize,
        tda: usize,
    ) -> _gsl_matrix_const_view;
}
extern "C" {
    pub fn gsl_matrix_set_zero(m: *mut gsl_matrix);
}
extern "C" {
    pub fn gsl_matrix_set_identity(m: *mut gsl_matrix);
}
extern "C" {
    pub fn gsl_matrix_set_all(m: *mut gsl_matrix, x: f64);
}
extern "C" {
    pub fn gsl_matrix_fread(stream: *mut FILE, m: *mut gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_fwrite(stream: *mut FILE, m: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_fscanf(stream: *mut FILE, m: *mut gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_fprintf(
        stream: *mut FILE,
        m: *const gsl_matrix,
        format: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_memcpy(
        dest: *mut gsl_matrix,
        src: *const gsl_matrix,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_swap(m1: *mut gsl_matrix, m2: *mut gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_tricpy(
        uplo_src: ::std::os::raw::c_char,
        copy_diag: ::std::os::raw::c_int,
        dest: *mut gsl_matrix,
        src: *const gsl_matrix,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_swap_rows(m: *mut gsl_matrix, i: usize, j: usize) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_swap_columns(m: *mut gsl_matrix, i: usize, j: usize)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_swap_rowcol(m: *mut gsl_matrix, i: usize, j: usize) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_transpose(m: *mut gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_transpose_memcpy(
        dest: *mut gsl_matrix,
        src: *const gsl_matrix,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_transpose_tricpy(
        uplo_src: ::std::os::raw::c_char,
        copy_diag: ::std::os::raw::c_int,
        dest: *mut gsl_matrix,
        src: *const gsl_matrix,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_max(m: *const gsl_matrix) -> f64;
}
extern "C" {
    pub fn gsl_matrix_min(m: *const gsl_matrix) -> f64;
}
extern "C" {
    pub fn gsl_matrix_minmax(m: *const gsl_matrix, min_out: *mut f64, max_out: *mut f64);
}
extern "C" {
    pub fn gsl_matrix_max_index(m: *const gsl_matrix, imax: *mut usize, jmax: *mut usize);
}
extern "C" {
    pub fn gsl_matrix_min_index(m: *const gsl_matrix, imin: *mut usize, jmin: *mut usize);
}
extern "C" {
    pub fn gsl_matrix_minmax_index(
        m: *const gsl_matrix,
        imin: *mut usize,
        jmin: *mut usize,
        imax: *mut usize,
        jmax: *mut usize,
    );
}
extern "C" {
    pub fn gsl_matrix_equal(a: *const gsl_matrix, b: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_isnull(m: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_ispos(m: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_isneg(m: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_isnonneg(m: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_add(a: *mut gsl_matrix, b: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_sub(a: *mut gsl_matrix, b: *const gsl_matrix) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_mul_elements(
        a: *mut gsl_matrix,
        b: *const gsl_matrix,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_div_elements(
        a: *mut gsl_matrix,
        b: *const gsl_matrix,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_scale(a: *mut gsl_matrix, x: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_add_constant(a: *mut gsl_matrix, x: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_add_diagonal(a: *mut gsl_matrix, x: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_get_row(
        v: *mut gsl_vector,
        m: *const gsl_matrix,
        i: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_get_col(
        v: *mut gsl_vector,
        m: *const gsl_matrix,
        j: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_set_row(
        m: *mut gsl_matrix,
        i: usize,
        v: *const gsl_vector,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_set_col(
        m: *mut gsl_matrix,
        j: usize,
        v: *const gsl_vector,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_matrix_get(m: *const gsl_matrix, i: usize, j: usize) -> f64;
}
extern "C" {
    pub fn gsl_matrix_set(m: *mut gsl_matrix, i: usize, j: usize, x: f64);
}
extern "C" {
    pub fn gsl_matrix_ptr(m: *mut gsl_matrix, i: usize, j: usize) -> *mut f64;
}
extern "C" {
    pub fn gsl_matrix_const_ptr(m: *const gsl_matrix, i: usize, j: usize) -> *const f64;
}
