use crate::gsl::vector_double::*;
use crate::gsl::matrix_double::*;
use crate::gsl::wavelet::*;

/* automatically generated by rust-bindgen */

extern "C" {
    pub fn gsl_wavelet2d_transform(
        w: *const gsl_wavelet,
        data: *mut f64,
        tda: usize,
        size1: usize,
        size2: usize,
        dir: gsl_wavelet_direction,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_transform_forward(
        w: *const gsl_wavelet,
        data: *mut f64,
        tda: usize,
        size1: usize,
        size2: usize,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_transform_inverse(
        w: *const gsl_wavelet,
        data: *mut f64,
        tda: usize,
        size1: usize,
        size2: usize,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_nstransform(
        w: *const gsl_wavelet,
        data: *mut f64,
        tda: usize,
        size1: usize,
        size2: usize,
        dir: gsl_wavelet_direction,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_nstransform_forward(
        w: *const gsl_wavelet,
        data: *mut f64,
        tda: usize,
        size1: usize,
        size2: usize,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_nstransform_inverse(
        w: *const gsl_wavelet,
        data: *mut f64,
        tda: usize,
        size1: usize,
        size2: usize,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_transform_matrix(
        w: *const gsl_wavelet,
        a: *mut gsl_matrix,
        dir: gsl_wavelet_direction,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_transform_matrix_forward(
        w: *const gsl_wavelet,
        a: *mut gsl_matrix,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_transform_matrix_inverse(
        w: *const gsl_wavelet,
        a: *mut gsl_matrix,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_nstransform_matrix(
        w: *const gsl_wavelet,
        a: *mut gsl_matrix,
        dir: gsl_wavelet_direction,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_nstransform_matrix_forward(
        w: *const gsl_wavelet,
        a: *mut gsl_matrix,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gsl_wavelet2d_nstransform_matrix_inverse(
        w: *const gsl_wavelet,
        a: *mut gsl_matrix,
        work: *mut gsl_wavelet_workspace,
    ) -> ::std::os::raw::c_int;
}
